name: budgetting_app
description: A Simple Budgetting App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_facebook_auth: ^4.0.1
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  google_sign_in: ^5.2.3
  hive: ^2.0.4
  http: ^0.13.4
  path_provider: ^2.0.9
  provider: ^6.0.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: LondonTube
      fonts:
        - asset: assets/fonts/LondonTube.ttf

    - family: AndroidEuclid
      fonts:
        - asset: assets/fonts/AndroidEuclid-Medium.otf

    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

    - family: CurrencyIcons
      fonts:
        - asset: assets/fonts/CurrencyIcons.ttf
