name: expense_tracker
description: A Simple Budgetting App.
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.5.1 <4.0.0"

isar_version: &isar_version 3.1.0+1

dependencies:
  bloc: ^8.0.1
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  provider: ^6.0.1
  uuid: ^4.4.2
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  freezed: ^2.4.5
  isar_generator: *isar_version

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app-icons.ttf

    - family: ApfelGrotezk
      fonts:
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Regular.otf
          weight: 400
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Mittel.otf
          weight: 500
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Fett.otf
          weight: 600
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Satt.otf
          weight: 700                    

    - family: SpaceMono
      fonts:
        - asset: assets/fonts/spacemono.ttf
