name: budgetting_app
description: A Simple Budgetting App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  build_runner: ^2.1.1
  hive: ^2.0.4
  hive_generator: ^1.1.1
  path_provider: ^2.0.7
  provider: ^6.0.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Roman.ttf

    - family: AndroidEuclid
      fonts:
        - asset: fonts/AndroidEuclid-Medium.otf
        - weight: 400
        - asset: fonts/AndroidEuclid-Bold.otf
        - weight: 600

    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
