name: budgetting_app
description: A Simple Budgetting App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  bloc: ^8.0.1
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.0
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  google_sign_in: ^5.2.3
  hive: ^2.2.3
  http: ^1.2.2
  path_provider: ^2.1.4
  provider: ^6.0.1
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app-icons.ttf

    - family: Mabry
      fonts:
        - asset: assets/fonts/Mabry-Pro-Medium.ttf

    - family: SpaceMono
      fonts:
        - asset: assets/fonts/spacemono.ttf

    - family: Gopher
      fonts:
        - asset: assets/fonts/Gopher-Regular.ttf

    - family: circular
      fonts:
        - asset: assets/fonts/Circular-Light.otf
          weight: 300
        - asset: assets/fonts/Circular.otf
          weight: 400
        - asset: assets/fonts/Circular-Medium.otf
          weight: 500
        - asset: assets/fonts/Circular-Bold.otf
          weight: 600
