name: budgetting_app
description: A Simple Budgetting App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^10.1.0
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  google_sign_in: ^5.2.3
  hive: ^2.0.4
  http: ^0.13.4
  path_provider: ^2.0.9
  provider: ^6.0.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app-icons.ttf

    - family: Mabry
      fonts:
        - asset: assets/fonts/Mabry-Pro-Medium.ttf

    - family: SpaceMono
      fonts:
        - asset: assets/fonts/spacemono.ttf

    - family: Gopher
      fonts:
        - asset: assets/fonts/Gopher-Regular.ttf

    - family: circular
      fonts:
        - asset: assets/fonts/Circular-Light.otf
          weight: 300
        - asset: assets/fonts/Circular.otf
          weight: 400
        - asset: assets/fonts/Circular-Medium.otf
          weight: 500
        - asset: assets/fonts/Circular-Bold.otf
          weight: 600
