name: expense_tracker_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  http: ^1.2.2
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  realm: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 800                                        
    - family: Ojuju
      fonts:
        - asset: assets/fonts/Ojuju/Ojuju-Light.ttf
          weight: 300
        - asset: assets/fonts/Ojuju/Ojuju-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ojuju/Ojuju-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ojuju/Ojuju-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Ojuju/Ojuju-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ojuju/Ojuju-ExtraBold.ttf
          weight: 800                                        