name: budgetting_app
description: A Simple Budgetting App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  build_runner: ^2.1.1
  hive: ^2.0.4
  hive_generator: ^1.1.1
  path_provider: ^2.0.7
  provider: ^6.0.1
  uuid: ^3.0.5
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  supabase: ^0.2.13
  http: ^0.13.4
  flutter_email_sender: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: LondonTube
      fonts:
        - asset: assets/fonts/LondonTube.ttf

    - family: AndroidEuclid
      fonts:
        - asset: assets/fonts/AndroidEuclid-Medium.otf

    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

    - family: CurrencyIcons
      fonts:
        - asset: assets/fonts/CurrencyIcons.ttf
